language: c
sudo: false

matrix:
  include:
    - env: GHCVER=7.10.1 CABALVER=1.22 JOPTS="-j2"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1],sources: [hvr-ghc]}}
    - env: GHCVER=head CABALVER=head JOPTS="-j2"
      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}

  allow_failures:
    - env: GHCVER=head CABALVER=head JOPTS="-j2"

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - export CABAL=cabal-$CABALVER
  - ghc --version
  - $CABAL --version
  - travis_retry $CABAL update

install:
  - $CABAL install $JOPTS --dependencies-only

script:
  - $CABAL configure -v2 -fdeverror
  - $CABAL build $JOPTS

  # tests that a source-distribution can be generated
  - $CABAL sdist

  # check that the generated source-distribution can be built & installed
  - export SRC_TGZ=$($CABAL info . | awk '{print $2 ".tar.gz";exit}') ;
    if [ -f "dist/$SRC_TGZ" ]; then
       $CABAL install $JOPTS --force-reinstalls "dist/$SRC_TGZ";
    else
       echo "expected 'dist/$SRC_TGZ' not found";
       exit 1;
    fi

notifications:
  irc:
    channels:
      - "irc.freenode.org#clash-lang"
    skip_join: true
    template:
      - "\x0313ghc-tcplugins-extra\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"
